-- ==================================================================================
-- 1. LIMPEZA (Opcional, caso queira resetar tudo antes)
-- ==================================================================================
DELETE FROM CONVIDADO_RESERVA;
DELETE FROM RESERVA;
DELETE FROM QUARTO;
DELETE FROM CATEGORIA_QUARTO_COMODIDADE;
DELETE FROM COMODIDADE;
DELETE FROM CATEGORIA_QUARTO;
DELETE FROM HOSPEDE;
DELETE FROM FUNCIONARIO;
DELETE FROM USUARIO;
DELETE FROM CIDADE;
DELETE FROM ESTADO;

-- ==================================================================================
-- 2. ESTADOS E CIDADES
-- ==================================================================================
INSERT INTO ESTADO (NOME_ESTADO, UF) VALUES
('São Paulo', 'SP'),
('Rio de Janeiro', 'RJ'),
('Minas Gerais', 'MG'),
('Bahia', 'BA'),
('Santa Catarina', 'SC');

INSERT INTO CIDADE (NOME_CIDADE, UF) VALUES
('São Paulo', 'SP'),
('Botucatu', 'SP'),
('Campinas', 'SP'),
('Rio de Janeiro', 'RJ'),
('Belo Horizonte', 'MG'),
('Salvador', 'BA'),
('Florianópolis', 'SC');

-- ==================================================================================
-- 3. USUÁRIOS (Login do Sistema)
-- Senha padrão '123456' para todos
-- ==================================================================================
INSERT INTO USUARIO (ATIVO, EMAIL, SENHA, PAPEL_USUARIO) VALUES
-- Staff
(TRUE, 'admin@hotel.com', '123456', 'GERENTE'),
(TRUE, 'lucio@hotel.com', '123456', 'RECEPCIONISTA'),
(TRUE, 'ana@hotel.com', '123456', 'RECEPCIONISTA'),
-- Hóspedes com acesso ao sistema
(TRUE, 'roberto@gmail.com', '123456', 'HOSPEDE'),
(TRUE, 'fernanda@gmail.com', '123456', 'HOSPEDE'),
(TRUE, 'joao.silva@hotmail.com', '123456', 'HOSPEDE');

-- ==================================================================================
-- 4. FUNCIONÁRIOS
-- ==================================================================================
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, CARGO, ID_USUARIO) VALUES
('Carlos Gerente', '111.111.111-11', 'GERENTE', (SELECT ID_USUARIO FROM USUARIO WHERE EMAIL = 'admin@hotel.com')),
('Lucio Souza', '222.222.222-22', 'RECEPCIONISTA', (SELECT ID_USUARIO FROM USUARIO WHERE EMAIL = 'lucio@hotel.com')),
('Ana Clara', '333.333.333-33', 'RECEPCIONISTA', (SELECT ID_USUARIO FROM USUARIO WHERE EMAIL = 'ana@hotel.com'));

-- ==================================================================================
-- 5. HÓSPEDES
-- Alguns linkados a usuários (App), outros apenas cadastro local (Balcão)
-- ==================================================================================
INSERT INTO HOSPEDE (NOME_HOSPEDE, CPF_HOSPEDE, DATA_NASCIMENTO, TELEFONE_HOSPEDE, ID_CIDADE, ID_USUARIO) VALUES
-- Hóspedes com Login
('Roberto Almeida', '436.273.068-05', '1995-01-20', '(14) 99677-9702', (SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE = 'Botucatu'), (SELECT ID_USUARIO FROM USUARIO WHERE EMAIL = 'roberto@gmail.com')),
('Fernanda Costa', '827.378.530-01', '1993-05-15', '(15) 99999-9999', (SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE = 'Botucatu'), (SELECT ID_USUARIO FROM USUARIO WHERE EMAIL = 'fernanda@gmail.com')),
('João Silva', '999.888.777-66', '1980-12-10', '(11) 98888-7777', (SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE = 'São Paulo'), (SELECT ID_USUARIO FROM USUARIO WHERE EMAIL = 'joao.silva@hotmail.com')),
-- Hóspedes sem Login (Cadastrados na recepção)
('Maria Oliveira', '555.444.333-22', '1975-03-25', '(21) 97777-6666', (SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE = 'Rio de Janeiro'), NULL),
('Pedro Santos', '111.222.333-44', '1990-07-07', '(31) 96666-5555', (SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE = 'Belo Horizonte'), NULL);

-- ==================================================================================
-- 6. COMODIDADES E CATEGORIAS
-- ==================================================================================
INSERT INTO COMODIDADE (NOME_COMODIDADE, DESCRICAO_COMODIDADE) VALUES
('Wi-Fi', 'Internet de alta velocidade fibra ótica'),
('Ar Condicionado', 'Split 12000 BTUs'),
('TV Cabo', 'Smart TV 50 polegadas com canais a cabo'),
('Frigobar', 'Frigobar abastecido'),
('Hidromassagem', 'Banheira de hidromassagem para casal'),
('Vista Mar', 'Varanda com vista para o mar'),
('Cofre', 'Cofre digital para notebook'),
('Mesa de Trabalho', 'Mesa ergonômica para home office');

INSERT INTO CATEGORIA_QUARTO (NOME_CATEGORIA, DESCRICAO_CATEGORIA, MAX_HOSPEDES, VALOR_DIARIA, POSICAO_QUARTO) VALUES
('Standard', 'Quarto econômico ideal para solteiros ou casais rápidos', 2, 150.00, 'INTERNA'),
('Master', 'Quarto espaçoso com vista para o jardim', 3, 280.00, 'EXTERNA'),
('Deluxe', 'Suíte completa com hidromassagem', 2, 450.00, 'EXTERNA'),
('Presidencial', 'Experiência de luxo no último andar', 4, 1200.00, 'EXTERNA');

-- Vinculando Comodidades às Categorias
-- Standard: Wifi, Ar, TV
INSERT INTO CATEGORIA_QUARTO_COMODIDADE (ID_CATEGORIA, ID_COMODIDADE) VALUES
((SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Standard'), (SELECT ID_COMODIDADE FROM COMODIDADE WHERE NOME_COMODIDADE = 'Wi-Fi')),
((SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Standard'), (SELECT ID_COMODIDADE FROM COMODIDADE WHERE NOME_COMODIDADE = 'Ar Condicionado')),
((SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Standard'), (SELECT ID_COMODIDADE FROM COMODIDADE WHERE NOME_COMODIDADE = 'TV Cabo'));

-- Deluxe: Tudo do Standard + Frigobar + Hidro + Vista Mar
INSERT INTO CATEGORIA_QUARTO_COMODIDADE (ID_CATEGORIA, ID_COMODIDADE) VALUES
((SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Deluxe'), (SELECT ID_COMODIDADE FROM COMODIDADE WHERE NOME_COMODIDADE = 'Wi-Fi')),
((SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Deluxe'), (SELECT ID_COMODIDADE FROM COMODIDADE WHERE NOME_COMODIDADE = 'Ar Condicionado')),
((SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Deluxe'), (SELECT ID_COMODIDADE FROM COMODIDADE WHERE NOME_COMODIDADE = 'TV Cabo')),
((SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Deluxe'), (SELECT ID_COMODIDADE FROM COMODIDADE WHERE NOME_COMODIDADE = 'Frigobar')),
((SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Deluxe'), (SELECT ID_COMODIDADE FROM COMODIDADE WHERE NOME_COMODIDADE = 'Hidromassagem')),
((SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Deluxe'), (SELECT ID_COMODIDADE FROM COMODIDADE WHERE NOME_COMODIDADE = 'Vista Mar'));

-- ==================================================================================
-- 7. QUARTOS (INVENTÁRIO)
-- Bloco 1: Standard (Térreo) e Master (1º Andar)
-- Bloco 2: Deluxe (Cobertura)
-- ==================================================================================
INSERT INTO QUARTO (NUM_BLOCO, NUM_ANDAR, NUM_APARTAMENTO, ID_CATEGORIA, STATUS_QUARTO) VALUES
-- Standard (Bloco 1, Térreo)
(1, 0, 101, (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Standard'), 'OCUPADO'), -- ATUALIZADO: Está ocupado pelo Pedro Santos
(1, 0, 102, (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Standard'), 'DISPONIVEL'), -- Correto: Checkout realizado
(1, 0, 103, (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Standard'), 'OCUPADO'), -- Correto: Ocupado pela Fernanda
(1, 0, 104, (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Standard'), 'BLOQUEADO'), -- Correto: Manutenção

-- Master (Bloco 1, 1º Andar)
(1, 1, 201, (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Master'), 'DISPONIVEL'), -- Correto: Reserva futura apenas
(1, 1, 202, (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Master'), 'DISPONIVEL'),

-- Deluxe (Bloco 2, Cobertura)
(2, 5, 501, (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Deluxe'), 'DISPONIVEL'),
(2, 5, 502, (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Deluxe'), 'DISPONIVEL'); -- ATUALIZADO: Estava Ocupado, mas sem reserva vinculada. Alterado para Disponível.

-- ==================================================================================
-- 8. RESERVAS (COM DATA_INICIO E DATA_FIM COMO LOCALDATE - SEM HORA)
-- ==================================================================================

-- CENÁRIO 1: Reserva Finalizada (Checkout feito) - Quarto 102 (Standard)
INSERT INTO RESERVA (DATA_INICIO, DATA_FIM, DATA_CHECKIN, DATA_CHECKOUT, VALOR_RESERVA, FORMA_PAGAMENTO, STATUS_RESERVA, ID_CATEGORIA, ID_QUARTO, ID_HOSPEDE, ID_FUNCIONARIO) VALUES
    ('2023-10-01', '2023-10-05', '2023-10-01 14:15:00', '2023-10-05 11:30:00', 600.00, 'CREDITO', 'CHECKOUT',
     (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Standard'),
     (SELECT ID_QUARTO FROM QUARTO WHERE NUM_APARTAMENTO = 102),
     (SELECT ID_HOSPEDE FROM HOSPEDE WHERE NOME_HOSPEDE LIKE 'Roberto%'),
     (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE NOME_FUNCIONARIO LIKE 'Lucio%'));

-- CENÁRIO 2: Reserva Ativa (Checkin feito) - Quarto 103 (Standard)
INSERT INTO RESERVA (DATA_INICIO, DATA_FIM, DATA_CHECKIN, DATA_CHECKOUT, VALOR_RESERVA, FORMA_PAGAMENTO, STATUS_RESERVA, ID_CATEGORIA, ID_QUARTO, ID_HOSPEDE, ID_FUNCIONARIO) VALUES
    (CURRENT_DATE, DATEADD('DAY', 3, CURRENT_DATE), CURRENT_TIMESTAMP, NULL, 450.00, 'PIX', 'CHECKIN',
     (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Standard'),
     (SELECT ID_QUARTO FROM QUARTO WHERE NUM_APARTAMENTO = 103),
     (SELECT ID_HOSPEDE FROM HOSPEDE WHERE NOME_HOSPEDE LIKE 'Fernanda%'),
     (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE NOME_FUNCIONARIO LIKE 'Ana%'));

-- CENÁRIO 3: Reserva Futura Confirmada (SEM Quarto atribuído ainda)
INSERT INTO RESERVA (DATA_INICIO, DATA_FIM, DATA_CHECKIN, DATA_CHECKOUT, VALOR_RESERVA, FORMA_PAGAMENTO, STATUS_RESERVA, ID_CATEGORIA, ID_QUARTO, ID_HOSPEDE, ID_FUNCIONARIO) VALUES
    (DATEADD('MONTH', 1, CURRENT_DATE), DATEADD('DAY', 5, DATEADD('MONTH', 1, CURRENT_DATE)), NULL, NULL, 1400.00, 'CREDITO', 'RESERVADO',
     (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Master'),
     NULL,
     (SELECT ID_HOSPEDE FROM HOSPEDE WHERE NOME_HOSPEDE LIKE 'João%'),
     (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE NOME_FUNCIONARIO LIKE 'Lucio%'));

-- CENÁRIO 4: Reserva Cancelada
INSERT INTO RESERVA (DATA_INICIO, DATA_FIM, DATA_CHECKIN, DATA_CHECKOUT, VALOR_RESERVA, FORMA_PAGAMENTO, STATUS_RESERVA, ID_CATEGORIA, ID_QUARTO, ID_HOSPEDE, ID_FUNCIONARIO) VALUES
    (DATEADD('DAY', 10, CURRENT_DATE), DATEADD('DAY', 12, CURRENT_DATE), NULL, NULL, 300.00, 'DINHEIRO', 'CANCELADO',
     (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Standard'),
     NULL,
     (SELECT ID_HOSPEDE FROM HOSPEDE WHERE NOME_HOSPEDE LIKE 'Pedro%'),
     (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE NOME_FUNCIONARIO LIKE 'Lucio%'));

-- CENÁRIO 5: HISTÓRICO: Maria Oliveira
INSERT INTO RESERVA (DATA_INICIO, DATA_FIM, DATA_CHECKIN, DATA_CHECKOUT, VALOR_RESERVA, FORMA_PAGAMENTO, STATUS_RESERVA, ID_CATEGORIA, ID_QUARTO, ID_HOSPEDE, ID_FUNCIONARIO) VALUES
    ('2023-09-10', '2023-09-12', '2023-09-10 15:30:00', '2023-09-12 10:00:00', 300.00, 'DINHEIRO', 'CHECKOUT',
     (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Standard'),
     (SELECT ID_QUARTO FROM QUARTO WHERE NUM_APARTAMENTO = 101),
     (SELECT ID_HOSPEDE FROM HOSPEDE WHERE NOME_HOSPEDE LIKE 'Maria%'),
     (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE NOME_FUNCIONARIO LIKE 'Lucio%'));

-- CENÁRIO 6: FUTURO: Pedro Santos para o Natal
INSERT INTO RESERVA (DATA_INICIO, DATA_FIM, DATA_CHECKIN, DATA_CHECKOUT, VALOR_RESERVA, FORMA_PAGAMENTO, STATUS_RESERVA, ID_CATEGORIA, ID_QUARTO, ID_HOSPEDE, ID_FUNCIONARIO) VALUES
    ('2023-12-24', '2023-12-27', NULL, NULL, 840.00, 'CREDITO', 'RESERVADO',
     (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Master'),
     NULL,
     (SELECT ID_HOSPEDE FROM HOSPEDE WHERE NOME_HOSPEDE LIKE 'Pedro%'),
     (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE NOME_FUNCIONARIO LIKE 'Ana%'));

-- CENÁRIO 7: CANCELADO: João Silva em Agosto
INSERT INTO RESERVA (DATA_INICIO, DATA_FIM, DATA_CHECKIN, DATA_CHECKOUT, VALOR_RESERVA, FORMA_PAGAMENTO, STATUS_RESERVA, ID_CATEGORIA, ID_QUARTO, ID_HOSPEDE, ID_FUNCIONARIO) VALUES
    ('2023-08-01', '2023-08-05', NULL, NULL, 1800.00, 'PIX', 'CANCELADO',
     (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Deluxe'),
     NULL,
     (SELECT ID_HOSPEDE FROM HOSPEDE WHERE NOME_HOSPEDE LIKE 'João%'),
     (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE NOME_FUNCIONARIO LIKE 'Carlos%'));

-- CENÁRIO 8: FUTURO COM QUARTO: Roberto Almeida para semana que vem
INSERT INTO RESERVA (DATA_INICIO, DATA_FIM, DATA_CHECKIN, DATA_CHECKOUT, VALOR_RESERVA, FORMA_PAGAMENTO, STATUS_RESERVA, ID_CATEGORIA, ID_QUARTO, ID_HOSPEDE, ID_FUNCIONARIO) VALUES
    (DATEADD('DAY', 7, CURRENT_DATE), DATEADD('DAY', 10, CURRENT_DATE), NULL, NULL, 840.00, 'VOUCHER', 'RESERVADO',
     (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Master'),
     (SELECT ID_QUARTO FROM QUARTO WHERE NUM_APARTAMENTO = 201),
     (SELECT ID_HOSPEDE FROM HOSPEDE WHERE NOME_HOSPEDE LIKE 'Roberto%'),
     (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE NOME_FUNCIONARIO LIKE 'Lucio%'));

-- CENÁRIO 9: HISTÓRICO ANTIGO: Fernanda Costa no Reveillon
INSERT INTO RESERVA (DATA_INICIO, DATA_FIM, DATA_CHECKIN, DATA_CHECKOUT, VALOR_RESERVA, FORMA_PAGAMENTO, STATUS_RESERVA, ID_CATEGORIA, ID_QUARTO, ID_HOSPEDE, ID_FUNCIONARIO) VALUES
    ('2022-12-31', '2023-01-02', '2022-12-31 18:00:00', '2023-01-02 11:00:00', 2400.00, 'CREDITO', 'CHECKOUT',
     (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Presidencial'),
     NULL,
     (SELECT ID_HOSPEDE FROM HOSPEDE WHERE NOME_HOSPEDE LIKE 'Fernanda%'),
     (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE NOME_FUNCIONARIO LIKE 'Carlos%'));

-- CENÁRIO 10: CHECKIN HOJE: Walk-in do Pedro Santos
-- O quarto 101 foi atribuído aqui com CHECKIN, portanto deve estar OCUPADO.
INSERT INTO RESERVA (DATA_INICIO, DATA_FIM, DATA_CHECKIN, DATA_CHECKOUT, VALOR_RESERVA, FORMA_PAGAMENTO, STATUS_RESERVA, ID_CATEGORIA, ID_QUARTO, ID_HOSPEDE, ID_FUNCIONARIO) VALUES
    (CURRENT_DATE, DATEADD('DAY', 1, CURRENT_DATE), CURRENT_TIMESTAMP, NULL, 150.00, 'DEBITO', 'CHECKIN',
     (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Standard'),
     (SELECT ID_QUARTO FROM QUARTO WHERE NUM_APARTAMENTO = 101),
     (SELECT ID_HOSPEDE FROM HOSPEDE WHERE NOME_HOSPEDE LIKE 'Pedro%'),
     (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE NOME_FUNCIONARIO LIKE 'Ana%'));

-- CENÁRIO 11: Para testar filtro de checkout. Sera retornando tanto para CHECKOUT como para DISPONIVEL, no sentido de que o quarto pode estar limpo ou nao mas está disponível
INSERT INTO RESERVA (DATA_INICIO, DATA_FIM, DATA_CHECKIN, DATA_CHECKOUT, VALOR_RESERVA, FORMA_PAGAMENTO, STATUS_RESERVA, ID_CATEGORIA, ID_QUARTO, ID_HOSPEDE, ID_FUNCIONARIO) VALUES
    (
        DATEADD('DAY', -3, CURRENT_DATE), -- Chegou 3 dias atrás
        CURRENT_DATE,                     -- Data Fim é HOJE
        DATEADD('DAY', -3, CURRENT_TIMESTAMP),
        CURRENT_TIMESTAMP,                -- Saiu agora mesmo
        1350.00,
        'PIX',
        'CHECKOUT',
        (SELECT ID_CATEGORIA FROM CATEGORIA_QUARTO WHERE NOME_CATEGORIA = 'Deluxe'),
        (SELECT ID_QUARTO FROM QUARTO WHERE NUM_APARTAMENTO = 501),
        (SELECT ID_HOSPEDE FROM HOSPEDE WHERE NOME_HOSPEDE LIKE 'Maria%'),
        (SELECT ID_FUNCIONARIO FROM FUNCIONARIO WHERE NOME_FUNCIONARIO LIKE 'Lucio%')
    );